[tool.poetry]
name = "pricing-engine"
version = "0.0.2"
description = "Pricing Engine"
authors = ["DaRekaze <darekaze@gmail.com>"]
readme = "README.md"
packages = [
    { include = "pricing_engine"},
]

[tool.poetry.dependencies]
python = "^3.8"
httpx = {extras = ["http2", "socks"], version = ">=0.21.0"}
aiometer = ">=0.3.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1"
black = {version = "^21.12b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
